### PR TITLE
Fix CI issues

### PR DESCRIPTION
**Pull request by gowthamsk-arm**
Signed-off-by: Gowtham Suresh Kumar <gowtham.sureshkumar@arm.com>

### CODE REVIEW

**Comment by gowthamsk-arm** [comment]
CI failure will be fixed in this MR.
https://github.com/parallaxsecond/parsec-interface-rs/pull/135

**Review by ionut-arm — APPROVED** [review]
👍🏻

**Review by mohamedasaker-arm — APPROVED** [review]
👍🏼

**Comment by mohamedasaker-arm** [comment]
> 👍🏼

It feels like I am copying @ionut-arm 😅

**Pull request merged**
